#!/usr/bin/env python3
"""site-pages.py — las páginas del sitio que se GENERAN del árbol al pin (arco A11, W4).

Tres familias de páginas, en inglés como todo el sitio (QADR-0007), que nadie
escribe a mano: las escribe este script desde ficheros que ya existen, y el
guard umbrella-generated-pages (scripts/check_generated_pages.sh, que llama a
este script con --check) las regenera en memoria y falla si lo publicado no es
lo que el pin da.

  api       website/docs/reference/api-{nucleus,quark,orbit}.md — la superficie
            pública CONGELADA de cada producto, leída de los ficheros que el
            propio CI del producto compara con su código, al pin:
              nucleus  contracts/baseline/api_exported_symbols.txt
                       (+ contracts/baseline/extension_surface.txt)
              quark    acceptance/apisurface.json (con firmas y alias si el
                       pin las trae)
              orbit    contracts/baseline/api_exported_symbols.txt
            Ninguna lista escrita aquí: si el producto congela un símbolo más,
            la página lo tiene en cuanto el set re-pina.
  catalog   website/docs/reference/catalog.md — lo que `nucleus add` y
            `nucleus new --with` resuelven por nombre, leído de la TABLA que
            lee el CLI al pin (nucleus/internal/knownproviders/*.go, parseada
            como datos: literales compuestos de los tipos con Name y Module).
            Lee las dos formas de la tabla: los mapas por subsistema de
            nucleus ≤ v1.31.0 y la tabla única del catálogo (ADR-034) que trae
            el siguiente re-pin. Una columna que la tabla al pin no registra no
            se inventa: no sale.
  releases  website/releases/quantum-X-Y-Z.md — un post por set certificado:
            cada tag vX.Y.Z del paraguas (su versions.yaml) y el set que
            declara versions.yaml si todavía no tiene tag (el PR de set). El
            post dice qué fija el set y qué se movió desde el anterior, con los
            enlaces a las notas de cada producto. La narrativa del set
            (`notes:` y CHANGELOG.md) está en español (QADR-0009) y el sitio en
            inglés: el post no la traduce, enlaza el versions.yaml del tag que
            la lleva y, desde 1.30.0, la release con el paquete firmado (dos
            tags antiguos, v1.3.0 y v1.23.0, no tienen release en GitHub: por
            eso el enlace fijo es el manifiesto y no la release).

El script es dueño de los dos directorios: website/docs/reference/ y
website/releases/ sólo contienen lo que él escribe (una página a mano va a
website/docs/), y eso es lo que deja al tren meterlos enteros en el PR de set
(RUTAS_REPIN de scripts/train/train.sh).

Uso (desde cualquier sitio):
  python3 scripts/lib/site-pages.py                    escribe las tres familias
  python3 scripts/lib/site-pages.py --check            no escribe: falla con la deriva
  python3 scripts/lib/site-pages.py --check catalog    sólo una familia (api|catalog|releases)

EXIT 0 al día · 1 deriva o fuente ilegible · 2 error de uso.
Compatibilidad: python3 >= 3.8, sólo stdlib; git para los tags del paraguas.
"""
import difflib
import json
import os
import re
import subprocess
import sys
from collections import OrderedDict

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
GH = 'https://github.com/jcsvwinston'
OWNER = 'github.com/jcsvwinston'
REPOS = ('nucleus', 'quark', 'orbit')
TITLES = {'nucleus': 'Nucleus', 'quark': 'Quark', 'orbit': 'Orbit'}
REF_DIR = 'website/docs/reference'
POSTS_DIR = 'website/releases'
MARK = ('<!-- Generated by scripts/lib/site-pages.py from the tree at the pin. '
        'Do not edit: run python3 scripts/lib/site-pages.py -->')
# Directorios con go.mod que no son módulos publicados (el mismo filtro que
# scripts/lib/manifest-modules.sh y manifest-guard §3b).
SKIP_DIRS = {'examples', 'website', 'benchmarks', 'bugbash', 'acceptance', '.git', 'node_modules'}


class SourceError(Exception):
    """Una fuente que no se puede leer: la página no se puede generar."""


def rd(rel):
    path = os.path.join(ROOT, rel)
    if not os.path.isfile(path):
        raise SourceError(f'falta {rel} — sin la fuente no hay página que generar (¿submódulos sin inicializar?)')
    with open(path, encoding='utf-8') as f:
        return f.read()


# --------------------------------------------------------------------------
# versions.yaml
# --------------------------------------------------------------------------

def manifest(text, where):
    """quantum, released y los cuatro bloques de versiones de un versions.yaml."""
    def scalar(key):
        m = re.search(rf'^{key}:[ \t]*"?([^"#\n]+?)"?[ \t]*(?:#.*)?$', text, re.M)
        return m.group(1).strip() if m else None

    def block(name):
        out = OrderedDict()
        lines = text.split('\n')
        try:
            i = lines.index(f'{name}:')
        except ValueError:
            return out
        for line in lines[i + 1:]:
            if line.strip() == '' or line.lstrip().startswith('#'):
                continue
            if not line[0].isspace():
                break
            m = re.match(r'^\s+([A-Za-z0-9_-]+):\s*"([^"]+)"', line)
            if m:
                out[m.group(1)] = m.group(2)
        return out

    m = {'quantum': scalar('quantum'), 'released': scalar('released'),
         'modules': block('modules')}
    for repo in REPOS:
        m[repo] = block(f'{repo}_modules')
    if not m['quantum'] or not re.match(r'^\d+\.\d+\.\d+$', m['quantum']):
        raise SourceError(f'{where}: no declara «quantum:» con una versión X.Y.Z')
    if not m['released'] or not re.match(r'^\d{4}-\d{2}-\d{2}$', m['released']):
        raise SourceError(f'{where}: no declara «released:» con una fecha AAAA-MM-DD')
    for repo in REPOS:
        if not m['modules'].get(repo):
            raise SourceError(f'{where}: el bloque modules no fija {repo}')
    return m


def semver(v):
    return tuple(int(x) for x in v.lstrip('v').split('-')[0].split('.'))


def change(old, new):
    if old is None and new is None:
        return '—'
    if old is None:
        return 'new'
    if new is None:
        return 'removed'
    a, b = semver(old), semver(new)
    if a == b:
        return '—'
    if b < a:
        return 'downgrade'
    if b[0] != a[0]:
        return 'major'
    if b[1] != a[1]:
        return 'minor'
    return 'patch'


# --------------------------------------------------------------------------
# módulos de cada producto al pin: de la ruta de un paquete a su versión
# --------------------------------------------------------------------------

def product_modules(repo, pin):
    """{ruta de módulo: versión del set} de todo go.mod publicado del producto."""
    base = os.path.join(ROOT, repo)
    if not os.path.isdir(base):
        raise SourceError(f'falta el submódulo {repo}/')
    found = {}
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        if 'go.mod' not in filenames:
            continue
        with open(os.path.join(dirpath, 'go.mod'), encoding='utf-8') as f:
            m = re.search(r'^module\s+(\S+)', f.read(), re.M)
        if not m:
            continue
        rel = os.path.relpath(dirpath, base).replace(os.sep, '/')
        if rel == '.':
            found[m.group(1)] = pin['modules'][repo]
        else:
            ver = pin[repo].get(rel.split('/')[-1])
            if ver:
                found[m.group(1)] = ver
    root = f'{OWNER}/{repo}'
    if root not in found:
        raise SourceError(f'{repo}/go.mod no declara el módulo {root}')
    return found


def module_of(pkg, modules):
    best = None
    for mod in modules:
        if pkg == mod or pkg.startswith(mod + '/'):
            if best is None or len(mod) > len(best):
                best = mod
    return best


# --------------------------------------------------------------------------
# escapes para MDX (Docusaurus lee .md como MDX)
# --------------------------------------------------------------------------

def prose(s):
    return (s.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
             .replace('{', '&#123;').replace('}', '&#125;'))


def code(s):
    return f'`` {s} ``' if '`' in s else f'`{s}`'


def cell(s):
    return s.replace('|', '\\|')


def num(n):
    return f'{n:,}'


def slug(s):
    return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')


def front(fields):
    out = ['---']
    for k, v in fields:
        if v is None:
            out.append(f'{k}: null')
        elif isinstance(v, bool):
            out.append(f'{k}: {"true" if v else "false"}')
        elif k in ('date', 'sidebar_position'):
            out.append(f'{k}: {v}')
        else:
            out.append(f'{k}: {json.dumps(v, ensure_ascii=False)}')
    out.append('---')
    return '\n'.join(out)


# --------------------------------------------------------------------------
# api — la superficie congelada de cada producto
# --------------------------------------------------------------------------

API = [
    {'repo': 'nucleus', 'format': 'baseline',
     'source': 'contracts/baseline/api_exported_symbols.txt',
     'extension': 'contracts/baseline/extension_surface.txt',
     'how': ("Nucleus's CI compares this file with the code on every change and fails when "
             'they differ, so adding or removing an exported symbol means changing the file '
             'in the same change.')},
    {'repo': 'quark', 'format': 'apisurface',
     'source': 'acceptance/apisurface.json',
     'how': ('Quark regenerates this file from the code in CI and fails a change whose '
             'committed copy differs, so adding or removing an exported symbol means changing '
             'the file in the same change.')},
    {'repo': 'orbit', 'format': 'baseline',
     'source': 'contracts/baseline/api_exported_symbols.txt',
     'how': ("Orbit's CI compares this file with the code on every change and fails when "
             'they differ, so adding or removing an exported symbol means changing the file '
             'in the same change.')},
]

KIND_ORDER = ('type', 'func', 'const', 'var')


def new_pkg():
    return {'types': OrderedDict(), 'func': [], 'const': [], 'var': []}


def type_entry(pkg, name):
    t = pkg['types'].get(name)
    if t is None:
        t = {'sig': None, 'alias_of': None, 'interface': False, 'fields': [], 'methods': []}
        pkg['types'][name] = t
    return t


def read_surface(spec):
    """{paquete: estructura} desde el fichero congelado del producto."""
    text = rd(f"{spec['repo']}/{spec['source']}")
    pkgs = OrderedDict()
    n = 0
    if spec['format'] == 'baseline':
        for i, line in enumerate(text.splitlines(), 1):
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            m = re.match(r'^(\S+)\s+([a-z-]+):(\S+)$', line)
            if not m:
                raise SourceError(f"{spec['repo']}/{spec['source']}:{i}: línea con forma desconocida «{line}»")
            pkg, kind, name = m.groups()
            p = pkgs.setdefault(pkg, new_pkg())
            n += 1
            if kind in ('method', 'field', 'iface-method'):
                typ, _, member = name.partition('.')
                if not member:
                    raise SourceError(f"{spec['repo']}/{spec['source']}:{i}: «{kind}:{name}» sin tipo")
                t = type_entry(p, typ)
                t['fields' if kind == 'field' else 'methods'].append((member, None))
                if kind == 'iface-method':
                    t['interface'] = True
            elif kind == 'type':
                type_entry(p, name)
            elif kind in ('func', 'const', 'var'):
                p[kind].append((name, None))
            else:
                raise SourceError(f"{spec['repo']}/{spec['source']}:{i}: clase de símbolo desconocida «{kind}»")
    else:
        try:
            symbols = json.loads(text)['symbols']
        except (ValueError, KeyError) as e:
            raise SourceError(f"{spec['repo']}/{spec['source']}: no es un inventario de símbolos ({e})")
        for s in symbols:
            pkg, kind, name = s.get('pkg'), s.get('kind'), s.get('name')
            if not (pkg and kind and name):
                raise SourceError(f"{spec['repo']}/{spec['source']}: símbolo sin pkg/kind/name: {s}")
            p = pkgs.setdefault(pkg, new_pkg())
            n += 1
            sig = s.get('sig')
            if kind in ('method', 'field'):
                m = re.match(r'^\(\*?([A-Za-z_]\w*)(?:\[[^\]]*\])?\)\.(\w+)$', name) or \
                    re.match(r'^([A-Za-z_]\w*)\.(\w+)$', name)
                if not m:
                    raise SourceError(f"{spec['repo']}/{spec['source']}: «{kind}» con nombre desconocido «{name}»")
                t = type_entry(p, m.group(1))
                t['fields' if kind == 'field' else 'methods'].append((m.group(2), sig))
            elif kind == 'type':
                t = type_entry(p, name)
                t['sig'] = sig
                t['alias_of'] = s.get('alias_of')
                if sig == 'interface':
                    t['interface'] = True
            elif kind in ('func', 'const', 'var'):
                p[kind].append((name, sig))
            else:
                raise SourceError(f"{spec['repo']}/{spec['source']}: clase de símbolo desconocida «{kind}»")
    if n == 0:
        raise SourceError(f"{spec['repo']}/{spec['source']}: cero símbolos — una página vacía no es una referencia")
    return pkgs, n


def short_alias(target, pkg):
    """quarkdriver.Check para el alias de otro paquete; el nombre solo si es el mismo."""
    path, _, name = target.rpartition('.')
    if path == pkg:
        return name
    return f"{path.rsplit('/', 1)[-1]}.{name}"


def member_list(members):
    if any(sig for _, sig in members):
        return None
    return ', '.join(code(m) for m, _ in members)


def render_api(spec, pin):
    repo = spec['repo']
    title = TITLES[repo]
    tag = pin['modules'][repo]
    suite = pin['quantum']
    pkgs, total = read_surface(spec)
    modules = product_modules(repo, pin)
    root_mod = f'{OWNER}/{repo}'

    def display(pkg):
        if pkg == root_mod:
            return repo
        return pkg[len(root_mod) + 1:] if pkg.startswith(root_mod + '/') else pkg

    def heading(pkg):
        return code(display(pkg)) + (' (module root)' if pkg == root_mod else '')

    for p in pkgs.values():
        p['types'] = OrderedDict(sorted(p['types'].items()))
        for t in p['types'].values():
            t['fields'].sort()
            t['methods'].sort()
        for kind in ('func', 'const', 'var'):
            p[kind].sort()

    counts = []
    for pkg, p in pkgs.items():
        c = {'types': len(p['types']),
             'functions': len(p['func']),
             'methods': sum(len(t['methods']) for t in p['types'].values()),
             'fields': sum(len(t['fields']) for t in p['types'].values()),
             'constants': len(p['const']),
             'variables': len(p['var'])}
        counts.append((pkg, c))
    columns = [k for k in ('types', 'functions', 'methods', 'fields', 'constants', 'variables')
               if any(c[k] for _, c in counts)]

    src_link = f"{GH}/{repo}/blob/{tag}/{spec['source']}"
    out = [front([
        ('title', f'{title} API surface'),
        ('sidebar_label', title),
        ('description', f'The exported Go API of {title} {tag} that its CI keeps frozen, '
                        f'generated from the file it compares the code with, at the version '
                        f'Quantum {suite} certifies.'),
        ('custom_edit_url', None),
    ]), '', MARK, '', f'# {title} API surface', '']
    out.append(
        f'The public Go API of **{title} {tag}**, the version Quantum {suite} certifies: '
        f'**{num(total)}** exported symbols in **{num(len(pkgs))}** packages. {title} keeps '
        f'this list in [`{spec["source"]}`]({src_link}). {spec["how"]} Removing an exported '
        f'symbol is a breaking change, and the suite ships breaking changes only in a major '
        f'version. This page is generated from that file at the pinned version, so it lists '
        f'exactly what the check protects.')
    out.append('')
    out.append('Each package links to its documentation on pkg.go.dev at this version, where '
               'every symbol has its signature and its comment.')
    out.append('')
    out.append('| Package | ' + ' | '.join(c.capitalize() for c in columns) + ' |')
    out.append('|---|' + '---:|' * len(columns))
    for pkg, c in counts:
        out.append(f'| [{heading(pkg)}](#{slug(display(pkg))}) | '
                   + ' | '.join(num(c[k]) if c[k] else '' for k in columns) + ' |')
    out.append('')

    for pkg, p in pkgs.items():
        mod = module_of(pkg, modules)
        if mod is None:
            raise SourceError(f'{repo}: el paquete {pkg} no pertenece a ningún módulo que el set certifique')
        sub = pkg[len(mod):]
        n_pkg = (len(p['types']) + len(p['func']) + len(p['const']) + len(p['var'])
                 + sum(len(t['methods']) + len(t['fields']) for t in p['types'].values()))
        out.append(f'## {heading(pkg)} {{#{slug(display(pkg))}}}')
        out.append('')
        out.append(f'`{pkg}` · {num(n_pkg)} symbols · '
                   f'[pkg.go.dev](https://pkg.go.dev/{mod}@{modules[mod]}{sub})')
        out.append('')
        if p['types']:
            out.append('**Types**')
            out.append('')
            for name, t in p['types'].items():
                head = f'- {code(name)}'
                if t['alias_of']:
                    head += f' = {code(short_alias(t["alias_of"], pkg))} (alias)'
                elif t['sig']:
                    head += f' {code(t["sig"])}'
                elif t['interface']:
                    head += ' interface'
                parts = []
                nested = []
                for label, key in (('fields', 'fields'), ('methods', 'methods')):
                    members = t[key]
                    if not members:
                        continue
                    flat = member_list(members)
                    if flat is not None:
                        parts.append(f'{label} {flat}')
                    else:
                        nested.extend(f'  - {code(m)}' + (f' {code(s)}' if s else '') for m, s in members)
                if parts:
                    head += ' — ' + '; '.join(parts)
                out.append(head)
                out.extend(nested)
            out.append('')
        for kind, label in (('func', 'Functions'), ('const', 'Constants'), ('var', 'Variables')):
            items = p[kind]
            if not items:
                continue
            flat = member_list(items)
            if flat is not None:
                out.append(f'**{label}** — {flat}')
            else:
                out.append(f'**{label}**')
                out.append('')
                out.extend(f'- {code(m)}' + (f' {code(s)}' if s else '') for m, s in items)
            out.append('')

    if spec.get('extension'):
        ext = [l.strip() for l in rd(f"{repo}/{spec['extension']}").splitlines()
               if l.strip() and not l.strip().startswith('#')]
        if not ext:
            raise SourceError(f"{repo}/{spec['extension']}: cero campos")
        ext_link = f"{GH}/{repo}/blob/{tag}/{spec['extension']}"
        out.append('## Fields an extension may rely on {#extension-surface}')
        out.append('')
        out.append(f'An `app.Extension` receives the whole `*app.App`. These are the **{num(len(ext))}** '
                   f'fields of `App` that {title} freezes for extensions, kept in '
                   f'[`{spec["extension"]}`]({ext_link}) and compared with the code by the same '
                   f'CI: removing one, or adding one without listing it, fails the build.')
        out.append('')
        out.extend(f'- {code(f)}' for f in ext)
        out.append('')
    return '\n'.join(out).rstrip('\n') + '\n'


# --------------------------------------------------------------------------
# catalog — la tabla que lee el CLI de nucleus, parseada como datos
# --------------------------------------------------------------------------

CATALOG_DIR = 'nucleus/internal/knownproviders'
GO_TOKEN = re.compile(r'''
    (?P<nl>\n) | (?P<ws>[ \t\r\f]+) | (?P<lc>//[^\n]*) | (?P<bc>/\*.*?\*/) |
    (?P<raw>`[^`]*`) | (?P<str>"(?:\\.|[^"\\\n])*") | (?P<rune>'(?:\\.|[^'\\\n])+') |
    (?P<num>\.?\d[\w.]*) | (?P<id>[A-Za-z_]\w*) |
    (?P<op>\.\.\.|:=|<-|&&|\|\||==|!=|<=|>=|<<|>>|[{}()\[\],:;.=+\-*/&|<>!^%~])
''', re.S | re.X)
GO_ESC = {'n': '\n', 't': '\t', 'r': '\r', '"': '"', '\\': '\\', "'": "'", 'a': '\a',
          'b': '\b', 'f': '\f', 'v': '\v'}


class GoParseError(SourceError):
    pass


def go_string(lit):
    if lit.startswith('`'):
        return lit[1:-1].replace('\r', '')
    body, out, i = lit[1:-1], [], 0
    while i < len(body):
        c = body[i]
        if c != '\\':
            out.append(c)
            i += 1
            continue
        e = body[i + 1]
        if e in GO_ESC:
            out.append(GO_ESC[e])
            i += 2
        elif e in 'uU':
            w = 4 if e == 'u' else 8
            out.append(chr(int(body[i + 2:i + 2 + w], 16)))
            i += 2 + w
        elif e == 'x':
            out.append(chr(int(body[i + 2:i + 4], 16)))
            i += 4
        else:
            raise ValueError(f'escape \\{e}')
    return ''.join(out)


class GoFile:
    """Lo justo de Go para leer una tabla de literales: tokens, constantes de
    cadena, structs y los `var` cuyo valor es un literal compuesto."""

    def __init__(self, path, text):
        self.path = path
        self.toks = []
        line, pos = 1, 0
        while pos < len(text):
            m = GO_TOKEN.match(text, pos)
            if not m:
                raise GoParseError(f'{path}:{line}: no sé leer «{text[pos:pos + 20]}»')
            kind, val = m.lastgroup, m.group()
            if kind in ('nl',) or (kind == 'bc' and '\n' in val):
                self.toks.append(('nl', '\n', line))
            elif kind not in ('ws', 'lc', 'bc'):
                self.toks.append((kind, val, line))
            line += val.count('\n')
            pos = m.end()
        self.toks.append(('eof', '', line))
        self.i = 0

    # -- navegación
    def peek(self, skip_nl=True, k=0):
        j = self.i
        while True:
            if skip_nl:
                while self.toks[j][0] == 'nl':
                    j += 1
            if k == 0 or self.toks[j][0] == 'eof':
                return self.toks[j]
            k -= 1
            j += 1

    def next(self, skip_nl=True):
        if skip_nl:
            while self.toks[self.i][0] == 'nl':
                self.i += 1
        t = self.toks[self.i]
        self.i += 1
        return t

    def expect(self, val):
        t = self.next()
        if t[1] != val:
            self.fail(t, f'esperaba «{val}»')
        return t

    def fail(self, tok, why):
        raise GoParseError(f'{self.path}:{tok[2]}: {why}, encontré «{tok[1]}» — '
                           'la tabla del catálogo cambió de forma; amplía el lector de scripts/lib/site-pages.py')

    def skip_balanced(self):
        """Salta desde un ( [ o { hasta su cierre."""
        pairs = {'(': ')', '[': ']', '{': '}'}
        t = self.next()
        stack = [pairs[t[1]]]
        while stack:
            t = self.next(skip_nl=False)
            if t[0] == 'eof':
                self.fail(t, 'fichero acabado dentro de un bloque')
            if t[0] == 'op' and t[1] in pairs:
                stack.append(pairs[t[1]])
            elif t[0] == 'op' and t[1] == stack[-1]:
                stack.pop()

    def skip_statement(self):
        """Salta hasta el final de la declaración (salto de línea a profundidad 0)."""
        while True:
            t = self.peek(skip_nl=False)
            if t[0] in ('nl', 'eof') or t[1] in (';', ')'):
                if t[0] == 'nl' or t[1] == ';':
                    self.next(skip_nl=False)
                return
            if t[0] == 'op' and t[1] in '([{':
                self.skip_balanced()
            else:
                self.next(skip_nl=False)

    # -- tipos
    def parse_type(self):
        t = self.next()
        if t[1] == '*':
            return ('ptr', self.parse_type())
        if t[1] == '[':
            if self.peek()[1] == ']':
                self.next()
                return ('slice', self.parse_type())
            while self.next()[1] != ']':
                pass
            return ('array', self.parse_type())
        if t[1] == 'map':
            self.expect('[')
            k = self.parse_type()
            self.expect(']')
            return ('map', k, self.parse_type())
        if t[1] in ('struct', 'interface', 'func'):
            if self.peek()[1] == '(':
                self.skip_balanced()
            if self.peek()[1] == '{':
                self.skip_balanced()
            return ('other', t[1])
        if t[0] == 'id':
            name = t[1]
            if self.peek()[1] == '.' and self.peek(k=1)[0] == 'id':
                self.next()
                name += '.' + self.next()[1]
            return ('named', name)
        self.fail(t, 'esperaba un tipo')


def go_scan(files):
    """Pasada 1: constantes de cadena, structs (con sus campos) y alias de tipo."""
    consts, structs, aliases = {}, {}, {}
    for g in files:
        g.i = 0
        while g.peek()[0] != 'eof':
            t = g.next()
            if t[0] != 'id' or t[1] not in ('const', 'type', 'var', 'func', 'import', 'package'):
                continue
            if t[1] == 'const':
                specs = []
                if g.peek()[1] == '(':
                    g.next()
                    while g.peek()[1] != ')':
                        specs.append(go_spec_tokens(g))
                    g.next()
                else:
                    specs.append(go_spec_tokens(g))
                for spec in specs:
                    go_const_spec(spec, consts)
            elif t[1] == 'type':
                decls = []
                if g.peek()[1] == '(':
                    g.next()
                    while g.peek()[1] != ')':
                        decls.append(g.next())
                        go_type_decl(g, decls[-1], structs, aliases)
                    g.next()
                else:
                    go_type_decl(g, g.next(), structs, aliases)
            elif t[1] == 'func':
                # la firma y el cuerpo: hasta la llave que abre el cuerpo
                while g.peek()[1] != '{' and g.peek()[0] != 'eof':
                    if g.peek()[1] in '([':
                        g.skip_balanced()
                    else:
                        g.next()
                if g.peek()[1] == '{':
                    g.skip_balanced()
            elif t[1] in ('import', 'var'):
                if g.peek()[1] == '(':
                    g.skip_balanced()
                else:
                    g.skip_statement()
    return consts, structs, aliases


def go_spec_tokens(g):
    """Los tokens de una especificación de const, hasta el salto de línea."""
    while g.peek(skip_nl=False)[0] == 'nl':
        g.next(skip_nl=False)
    toks, depth = [], 0
    while True:
        t = g.peek(skip_nl=False)
        if t[0] == 'eof' or (depth == 0 and (t[0] == 'nl' or t[1] == ';' or t[1] == ')')):
            if t[0] == 'nl' or t[1] == ';':
                g.next(skip_nl=False)
            return toks
        g.next(skip_nl=False)
        if t[1] in '([{':
            depth += 1
        elif t[1] in ')]}':
            depth -= 1
        if t[0] != 'nl':
            toks.append(t)


def go_const_spec(toks, consts):
    """NOMBRE [Tipo] = expresión de cadena; lo demás (iota, números) no interesa."""
    if '=' not in [t[1] for t in toks] or toks[0][0] != 'id':
        return
    eq = [t[1] for t in toks].index('=')
    names = [t[1] for t in toks[:eq] if t[0] == 'id']
    if len(names) > 2 or (len(names) == 2 and toks[1][1] == ','):
        return  # varias constantes en una línea: no hay ninguna de cadena así en la tabla
    val, ok = '', True
    rest = toks[eq + 1:]
    for k, t in enumerate(rest):
        if k % 2 == 1:
            ok = ok and t[1] == '+'
        elif t[0] in ('str', 'raw'):
            val += go_string(t[1])
        elif t[0] == 'id' and t[1] in consts:
            val += consts[t[1]]
        else:
            ok = False
    if ok and rest:
        consts[names[0]] = val


def go_type_decl(g, name_tok, structs, aliases):
    if g.peek()[1] == '=':
        g.next()
        aliases[name_tok[1]] = g.parse_type()
        return
    if g.peek()[1] == '[':  # parámetros de tipo
        g.skip_balanced()
    if g.peek()[1] == 'struct':
        g.next()
        g.expect('{')
        fields, at_line_start, depth = [], True, 0
        while True:
            t = g.next(skip_nl=False)
            if t[0] == 'eof':
                g.fail(t, 'struct sin cerrar')
            if t[0] == 'nl' or t[1] == ';':
                at_line_start = True
                continue
            if t[1] in '([{':
                depth += 1
            elif t[1] in ')]':
                depth -= 1
            elif t[1] == '}':
                if depth == 0:
                    break
                depth -= 1
            if at_line_start and depth == 0 and t[0] == 'id':
                fields.append(t[1])
            at_line_start = False
        structs[name_tok[1]] = fields
    else:
        typ = g.parse_type()
        if typ[0] == 'other' and g.peek()[1] == '{':
            g.skip_balanced()


def go_value(g, typ, ctx):
    """Un valor de campo de la tabla: cadenas (con + y constantes), bool, nil,
    números, []string{...} y literales de struct anidados."""
    t = g.peek()
    if t[1] == '&':
        g.next()
        return go_value(g, ('ptr', typ[1] if typ and typ[0] == 'ptr' else typ), ctx)
    if t[1] == '{':  # elemento con el tipo elidido
        elem = typ[1] if typ and typ[0] == 'ptr' else typ
        return go_composite(g, elem, ctx)
    if t[1] in ('[', 'map') or (t[0] == 'id' and g.peek(k=1)[1] in ('{', '.') and t[1] not in ctx['consts']):
        lit_type = g.parse_type()
        return go_composite(g, lit_type, ctx)
    if t[0] in ('str', 'raw') or (t[0] == 'id' and t[1] in ctx['consts']):
        s = ''
        while True:
            t = g.next()
            if t[0] in ('str', 'raw'):
                s += go_string(t[1])
            elif t[0] == 'id' and t[1] in ctx['consts']:
                s += ctx['consts'][t[1]]
            else:
                g.fail(t, 'esperaba una cadena o una constante de cadena')
            if g.peek()[1] != '+':
                return s
            g.next()
    if t[0] == 'id' and t[1] in ('true', 'false'):
        g.next()
        return t[1] == 'true'
    if t[0] == 'id' and t[1] == 'nil':
        g.next()
        return None
    if t[0] == 'num':
        g.next()
        return float(t[1]) if '.' in t[1] else int(t[1], 0)
    g.fail(t, 'valor que el lector de la tabla no sabe evaluar')


def resolve(typ, ctx):
    while typ and typ[0] == 'named' and typ[1] in ctx['aliases']:
        typ = ctx['aliases'][typ[1]]
    return typ


def go_composite(g, typ, ctx):
    typ = resolve(typ, ctx)
    g.expect('{')
    kind = typ[0] if typ else None
    if kind == 'named':
        out = OrderedDict([('_type', typ[1])])
        while g.peek()[1] != '}':
            key = g.next()
            if key[0] != 'id':
                g.fail(key, 'esperaba el nombre de un campo')
            g.expect(':')
            out[key[1]] = go_value(g, None, ctx)
            if g.peek()[1] == ',':
                g.next()
            elif g.peek()[1] != '}':
                g.fail(g.peek(), 'esperaba «,» o «}»')
        g.next()
        return out
    if kind in ('slice', 'array'):
        items = []
        while g.peek()[1] != '}':
            items.append(go_value(g, typ[-1], ctx))
            if g.peek()[1] == ',':
                g.next()
            elif g.peek()[1] != '}':
                g.fail(g.peek(), 'esperaba «,» o «}»')
        g.next()
        return items
    if kind == 'map':
        out = OrderedDict()
        while g.peek()[1] != '}':
            k = go_value(g, typ[1], ctx)
            g.expect(':')
            out[k] = go_value(g, typ[2], ctx)
            if g.peek()[1] == ',':
                g.next()
            elif g.peek()[1] != '}':
                g.fail(g.peek(), 'esperaba «,» o «}»')
        g.next()
        return out
    g.fail(g.peek(), f'literal de un tipo que la tabla no usa ({typ})')


def mentions(typ, names, ctx):
    typ = resolve(typ, ctx)
    if not typ:
        return False
    if typ[0] == 'named':
        return typ[1] in names
    return any(isinstance(x, tuple) and mentions(x, names, ctx) for x in typ[1:])


def read_var_spec(g, entry_types, ctx, entries):
    """Una especificación de `var`. Si su valor es un literal compuesto de un
    tipo que contiene entradas (map[string]Provider, []Entry…), se lee ENTERO
    y en estricto: lo que no sepa evaluar falla, no se salta. Lo demás se salta."""
    name = g.next()
    if name[0] != 'id':
        g.fail(name, 'esperaba el nombre de una variable')
    if g.peek(skip_nl=False)[1] == ',':
        g.skip_statement()
        return
    if g.peek(skip_nl=False)[1] != '=':
        if g.peek(skip_nl=False)[0] == 'nl':
            return
        g.parse_type()
        if g.peek(skip_nl=False)[1] != '=':
            g.skip_statement()
            return
    g.next()
    start = g.i
    lit_type = None
    if g.peek()[0] == 'id' or g.peek()[1] in ('[', '*'):
        try:
            lit_type = g.parse_type()
        except GoParseError:
            lit_type = None
    if lit_type is not None and g.peek(skip_nl=False)[1] == '{' and mentions(lit_type, entry_types, ctx):
        value = go_composite(g, lit_type, ctx)
        rows = value.items() if isinstance(value, dict) else ((None, v) for v in value)
        for key, v in rows:
            if not isinstance(v, dict) or v.get('_type') not in entry_types:
                g.fail(name, f'«var {name[1]}» mezcla filas que no son entradas')
            v = OrderedDict(v)
            v['_var'] = name[1]
            if key is not None:
                v['_mapkey'] = key
            v['_file'] = g.path
            entries.append(v)
        return
    g.i = start
    g.skip_statement()


def read_catalog():
    base = os.path.join(ROOT, CATALOG_DIR)
    if not os.path.isdir(base):
        raise SourceError(f'falta {CATALOG_DIR}/ — la tabla que lee `nucleus add` al pin')
    files = []
    for name in sorted(os.listdir(base)):
        if name.endswith('.go') and not name.endswith('_test.go'):
            files.append(GoFile(f'{CATALOG_DIR}/{name}', rd(f'{CATALOG_DIR}/{name}')))
    if not files:
        raise SourceError(f'{CATALOG_DIR}/ no tiene ficheros Go')
    consts, structs, aliases = go_scan(files)
    entry_types = {n for n, f in structs.items() if 'Name' in f and 'Module' in f}
    entry_types |= {n for n, a in aliases.items() if a[0] == 'named' and a[1] in entry_types}
    if not entry_types:
        raise SourceError(f'{CATALOG_DIR}: ningún struct con Name y Module — la tabla cambió de forma')
    ctx = {'consts': consts, 'aliases': aliases}
    entries = []
    for g in files:
        g.i = 0
        while g.peek()[0] != 'eof':
            t = g.next()
            if t[0] == 'id' and t[1] == 'func':
                while g.peek()[1] != '{' and g.peek()[0] != 'eof':
                    if g.peek()[1] in '([':
                        g.skip_balanced()
                    else:
                        g.next()
                if g.peek()[1] == '{':
                    g.skip_balanced()
                continue
            if not (t[0] == 'id' and t[1] == 'var'):
                continue
            if g.peek()[1] != '(':
                read_var_spec(g, entry_types, ctx, entries)
                continue
            g.next()
            while True:
                while g.peek(skip_nl=False)[0] == 'nl':
                    g.next(skip_nl=False)
                if g.peek()[1] == ')':
                    g.next()
                    break
                if g.peek()[0] == 'eof':
                    g.fail(g.peek(), 'bloque var sin cerrar')
                read_var_spec(g, entry_types, ctx, entries)
    if not entries:
        raise SourceError(f'{CATALOG_DIR}: la tabla no tiene ninguna entrada')
    return entries


GROUP_ORDER = ['database drivers', 'telemetry exporters', 'storage providers',
               'authentication backends', 'secrets resolvers']
SHIPS_TEXT = {
    'module': ('a module of the nucleus repository, published on its own so that an application '
               'links only what it uses: `nucleus add <name>` fetches it and writes the blank '
               'import that registers it'),
    'core': ('part of the framework module itself: there is nothing to fetch, and '
             '`nucleus add <name>` writes the wiring'),
    'suite': ('a sibling product of the suite (the admin panel, the ORM and the bridges between '
              'them): `nucleus new --with <name>` adds it to a new project'),
}


def plural(kind):
    if kind.endswith('s'):
        return kind
    if re.search(r'[^aeiou]y$', kind):
        return kind[:-1] + 'ies'
    return kind + 's'


def catalog_rows(entries, pin):
    nucleus_root = f'{OWNER}/nucleus'
    rows, seen = [], set()
    for e in entries:
        name, module = e.get('Name'), e.get('Module')
        if not name or not module:
            raise SourceError(f"{e['_file']}: una entrada de «{e['_var']}» sin Name o sin Module")
        if name in seen:
            raise SourceError(f'{CATALOG_DIR}: el nombre «{name}» está dos veces en la tabla')
        seen.add(name)
        ships = e.get('Ships')
        if not ships:
            if module == nucleus_root:
                ships = 'core'
            elif module.startswith(nucleus_root + '/'):
                ships = 'module'
            else:
                ships = 'suite'
        group = e.get('Group') or ('suite products' if ships == 'suite' else plural(e.get('Kind') or 'other'))
        version = module_version(module, pin)
        if version is None:
            raise SourceError(f'la tabla de `nucleus add` instala {module} ({name}) y el set no lo certifica '
                              '(versions.yaml): una página que lo publicara prometería un módulo fuera del set')
        rows.append({'name': name, 'ships': ships, 'group': group, 'module': module, 'version': version,
                     'entry': e})
    order = {g: i for i, g in enumerate(GROUP_ORDER)}
    groups = []
    for r in rows:
        if r['group'] not in groups:
            groups.append(r['group'])
    first = list(groups)
    groups.sort(key=lambda g: (g == 'suite products', order.get(g, len(order)), first.index(g)))
    return rows, groups


def module_version(module, pin):
    for repo in REPOS:
        root = f'{OWNER}/{repo}'
        if module == root:
            return pin['modules'][repo]
        if module.startswith(root + '/'):
            return pin[repo].get(module.rsplit('/', 1)[-1])
    return None


def render_catalog(pin):
    entries = read_catalog()
    rows, groups = catalog_rows(entries, pin)
    tag = pin['modules']['nucleus']
    suite = pin['quantum']
    out = [front([
        ('title', 'The nucleus add catalog'),
        ('sidebar_label', 'nucleus add catalog'),
        ('description', f'What nucleus add and nucleus new --with resolve by name in Nucleus {tag}, '
                        f'generated from the table the CLI reads, at the version Quantum {suite} certifies.'),
        ('custom_edit_url', None),
    ]), '', MARK, '', '# The `nucleus add` catalog', '']
    what = join_words([w for k, w in (('module', 'optional modules'), ('core', 'framework capabilities'),
                                      ('suite', 'suite products')) if any(r['ships'] == k for r in rows)])
    out.append(
        f'The {what} that `nucleus add <name>` '
        f'and `nucleus new --with <name>` resolve by name in **Nucleus {tag}**, the version '
        f'Quantum {suite} certifies: **{num(len(rows))}** entries. This page is generated from the '
        f'table the CLI reads, [`internal/knownproviders`]({GH}/nucleus/tree/{tag}/internal/knownproviders), '
        f'so a name is listed here exactly when that version of the CLI knows it, and each module '
        f'shows the version this set certifies.')
    out.append('')
    out.append('| Name | Ships as | Module | Version in this set |')
    out.append('|---|---|---|---|')
    for g in groups:
        for r in rows:
            if r['group'] == g:
                out.append(f"| [{code(r['name'])}](#{slug('entry-' + r['name'])}) | {r['ships']} | "
                           f"{code(r['module'])} | {r['version']} |")
    out.append('')
    out.append('**Ships as** says how an entry reaches an application:')
    out.append('')
    for ships in ('module', 'core', 'suite'):
        if any(r['ships'] == ships for r in rows):
            out.append(f'- **{ships}**: {SHIPS_TEXT[ships]}.')
    out.append('')
    for g in groups:
        out.append(f'## {prose(g[:1].upper() + g[1:])} {{#{slug("group-" + g)}}}')
        out.append('')
        for r in rows:
            if r['group'] != g:
                continue
            e = r['entry']
            out.append(f"### {code(r['name'])} {{#{slug('entry-' + r['name'])}}}")
            out.append('')
            lines = [f"- **Module**: {code(r['module'])}, {r['version']} in this set"]
            if e.get('Kind') and plural(e['Kind']) != g:
                lines.append(f"- **Kind**: {prose(e['Kind'])}")
            if e.get('Aliases'):
                lines.append('- **Also accepted as**: ' + ', '.join(code(a) for a in e['Aliases']))
            key = e.get('Key') or e.get('_mapkey')
            if key and key != r['name']:
                lines.append(f'- **Runtime name**: {code(key)}, the name the runtime looks it up by')
            if e.get('Import') and e['Import'] != r['module']:
                lines.append(f"- **Imports**: {code(e['Import'])}")
            if e.get('Selects'):
                lines.append(f"- **Selected by**: {prose(e['Selects'])}")
            if e.get('Wires'):
                lines.append(f"- **Wires**: {prose(e['Wires'])}")
            if e.get('Adds'):
                lines.append(f"- **Adds**: {prose(e['Adds'])}")
            if e.get('DriverModule'):
                lines.append(f"- **Driver module**: {code(e['DriverModule'].replace('%s', '<engine>'))}, "
                             'one per database engine')
            if e.get('RequiresConfig'):
                lines.append('- **Needs a configuration block of its own** to work')
            if e.get('Remote'):
                lines.append('- **Depends on a system outside the application**')
            recipe = e.get('Recipe')
            if isinstance(recipe, dict):
                if recipe.get('Chain'):
                    lines.append('- **Writes into `main.go`**: ' + ', '.join(code(c) for c in recipe['Chain']))
                if recipe.get('Routes'):
                    lines.append('- **Serves**: ' + ', '.join(code(c) for c in recipe['Routes']))
                if recipe.get('Then'):
                    lines.append('- **Left to you**: ' + '; '.join(prose(c) for c in recipe['Then']))
            out.extend(lines)
            if isinstance(recipe, dict) and recipe.get('Config'):
                out.append('')
                out.append('The configuration block `nucleus add` writes:')
                out.append('')
                out.append('```yaml')
                out.append(recipe['Config'].rstrip('\n'))
                out.append('```')
            out.append('')
    return '\n'.join(out).rstrip('\n') + '\n'


# --------------------------------------------------------------------------
# releases — un post por set certificado
# --------------------------------------------------------------------------

# La lane release-set (paquete del set firmado y atestado) publica desde el
# tag v1.30.0; los sets anteriores tienen tag y manifiesto, sin paquete.
BUNDLE_SINCE = (1, 30, 0)
RELEASE_NOTES = {r: f'/{r}/reference/release-notes' for r in REPOS}


def git(*args):
    r = subprocess.run(['git', '-C', ROOT] + list(args), capture_output=True, text=True)
    if r.returncode != 0:
        raise SourceError(f'git {" ".join(args)}: {r.stderr.strip() or "falló"}')
    return r.stdout


def certified_sets():
    """[(versión, manifiesto, tag o None)] en orden de versión."""
    tags = [t for t in git('tag', '--list', 'v*').split()
            if re.match(r'^v\d+\.\d+\.\d+$', t) and semver(t)[0] >= 1]
    if not tags:
        raise SourceError('el paraguas no tiene ningún tag de suite vX.Y.Z: sin historia no hay posts que '
                          'comparar (en CI, el checkout necesita fetch-depth: 0 para traer los tags)')
    sets = []
    for t in tags:
        m = manifest(git('show', f'{t}:versions.yaml'), f'versions.yaml en {t}')
        if m['quantum'] != t[1:]:
            raise SourceError(f'el tag {t} declara la suite {m["quantum"]} en su versions.yaml')
        sets.append((m['quantum'], m, t))
    current = manifest(rd('versions.yaml'), 'versions.yaml')
    if current['quantum'] not in {v for v, _, _ in sets}:
        if semver(current['quantum']) < max(semver(v) for v, _, _ in sets):
            raise SourceError(f'versions.yaml declara {current["quantum"]}, por debajo del último tag de suite')
        sets.append((current['quantum'], current, None))
    sets.sort(key=lambda s: semver(s[0]))
    return sets


def post_name(ver):
    return f'quantum-{ver.replace(".", "-")}'


def join_words(items):
    if len(items) <= 1:
        return ''.join(items)
    return ', '.join(items[:-1]) + ' and ' + items[-1]


def render_post(ver, m, prev, hour):
    pillars = [(r, m['modules'][r]) for r in REPOS]
    n_sib = sum(len(m[r]) for r in REPOS)
    pin_words = join_words([f'**{r} {v}**' for r, v in pillars])
    out = [front([
        ('title', f'Quantum {ver}'),
        ('description', f'Quantum {ver} certifies ' + join_words([f'{r} {v}' for r, v in pillars]) + '.'),
        ('date', f"{m['released']}T{hour:02d}:00:00Z"),
        ('slug', post_name(ver)),
        ('hide_table_of_contents', True),
    ]), '', MARK, '']
    lead = f'Quantum {ver} was certified on {m["released"]}. It pins {pin_words}'
    lead += f', with {num(n_sib)} sibling modules.' if n_sib else '.'
    out.append(lead)
    out.append('')
    if prev is None:
        out.append('It is the first set with a suite tag: the sets before it were recorded only as '
                   'commits of the manifest.')
    else:
        pver, pm = prev
        kind = change(pver, ver)
        moves, stays = [], []
        for r, v in pillars:
            old = pm['modules'][r]
            c = change(old, v)
            (stays if c == '—' else moves).append(
                f'{r} stays at {v}' if c == '—' else f'{r} goes from {old} to {v} ({c})')
        sentence = f'A {kind} release of the suite after Quantum {pver}: ' if kind in ('major', 'minor', 'patch') \
            else f'After Quantum {pver}: '
        sentence += join_words(moves + stays) + '.'
        moved = sum(1 for r in REPOS for k, v in m[r].items() if change(pm[r].get(k), v) != '—')
        moved += sum(1 for r in REPOS for k in pm[r] if k not in m[r])
        if n_sib or moved:
            sentence += (f' {num(moved)} sibling module{"s" if moved != 1 else ""} '
                         f'{"change" if moved != 1 else "changes"} version.' if moved
                         else ' No sibling module changes version.')
        out.append(sentence)
    out.append('')
    out.append('<!-- truncate -->')
    out.append('')
    out.append('## The products')
    out.append('')
    if prev is None:
        out.append(f'| Product | Quantum {ver} | Release notes |')
        out.append('|---|---|---|')
        for r, v in pillars:
            out.append(f'| {TITLES[r]} | {v} | [{v}]({GH}/{r}/releases/tag/{v}) · [all versions]({RELEASE_NOTES[r]}) |')
    else:
        pver, pm = prev
        out.append(f'| Product | Quantum {pver} | Quantum {ver} | Change | Release notes |')
        out.append('|---|---|---|---|---|')
        for r, v in pillars:
            old = pm['modules'][r]
            c = change(old, v)
            notes = (f'[changes]({GH}/{r}/compare/{old}...{v}) · [{v}]({GH}/{r}/releases/tag/{v}) · '
                     if c != '—' else '')
            out.append(f'| {TITLES[r]} | {old} | {v} | {c} | {notes}[all versions]({RELEASE_NOTES[r]}) |')
    out.append('')
    if n_sib or (prev is not None and any(prev[1][r] for r in REPOS)):
        out.append('## Sibling modules')
        out.append('')
        out.append('Each product publishes its optional pieces as modules of their own; a module is '
                   'named here by the last segment of its path, as in the manifest '
                   '([how keys map to paths](/start/certified-sets)).')
        out.append('')
        if prev is None:
            out.append('| Repository | Module | Version |')
            out.append('|---|---|---|')
        else:
            out.append(f'| Repository | Module | Version | Since {prev[0]} |')
            out.append('|---|---|---|---|')
        for r in REPOS:
            keys = list(m[r])
            if prev is not None:
                keys += [k for k in prev[1][r] if k not in m[r]]
            for k in sorted(keys):
                v = m[r].get(k)
                if prev is None:
                    out.append(f'| {r} | {code(k)} | {v} |')
                else:
                    out.append(f'| {r} | {code(k)} | {v or "—"} | {change(prev[1][r].get(k), v)} |')
        out.append('')
    out.append('## The manifest')
    out.append('')
    out.append(f'- The manifest of this set: [`versions.yaml` at v{ver}]({GH}/quantum/blob/v{ver}/versions.yaml). '
               'Its `notes:` field tells the story of the set, in Spanish, the working language of the '
               'project.')
    if semver(ver) >= BUNDLE_SINCE:
        out.append(f'- Its signed bundle (the manifest, the `require` block and their checksums): '
                   f'[GitHub release v{ver}]({GH}/quantum/releases/tag/v{ver}), and '
                   f'[how to verify it](/start/verifying-a-set).')
    else:
        out.append('- Sets before Quantum 1.30.0 have no signed bundle.')
    return '\n'.join(out).rstrip('\n') + '\n'


def render_posts():
    sets = certified_sets()
    pages, per_day, prev = OrderedDict(), {}, None
    for ver, m, _tag in sets:
        hour = per_day.get(m['released'], 0)
        if hour > 23:
            raise SourceError(f'más de 24 sets el {m["released"]}: el orden del blog por hora no alcanza')
        per_day[m['released']] = hour + 1
        pages[f'{POSTS_DIR}/{post_name(ver)}.md'] = render_post(ver, m, prev, hour)
        prev = (ver, m)
    return pages, sets


# --------------------------------------------------------------------------
# orquestación
# --------------------------------------------------------------------------

FAMILIES = ('api', 'catalog', 'releases')


def generate(families, pin):
    pages, owned, notes = OrderedDict(), [], {}
    if 'api' in families:
        for spec in API:
            pages[f"{REF_DIR}/api-{spec['repo']}.md"] = render_api(spec, pin)
        owned.append((REF_DIR, re.compile(r'^api-.*\.mdx?$')))
    if 'catalog' in families:
        pages[f'{REF_DIR}/catalog.md'] = render_catalog(pin)
        owned.append((REF_DIR, re.compile(r'^catalog\.mdx?$')))
    if 'releases' in families:
        posts, sets = render_posts()
        pages.update(posts)
        owned.append((POSTS_DIR, re.compile(r'.*')))
        notes['latest'] = sets[-1][0]
    if 'api' in families and 'catalog' in families:
        # el directorio entero es del generador: nada a mano dentro
        owned.append((REF_DIR, re.compile(r'.*')))
    return pages, owned, notes


def on_disk(owned):
    found = set()
    for d, pat in owned:
        full = os.path.join(ROOT, d)
        if not os.path.isdir(full):
            continue
        for name in os.listdir(full):
            if pat.match(name) and os.path.isfile(os.path.join(full, name)):
                found.add(f'{d}/{name}')
    return found


def main(argv):
    check = False
    families = []
    for a in argv:
        if a == '--check':
            check = True
        elif a in FAMILIES:
            families.append(a)
        elif a in ('-h', '--help'):
            print(__doc__)
            return 0
        else:
            print(f'site-pages: argumento desconocido «{a}» (--check, {"|".join(FAMILIES)})', file=sys.stderr)
            return 2
    families = families or list(FAMILIES)
    try:
        pin = manifest(rd('versions.yaml'), 'versions.yaml')
        pages, owned, notes = generate(families, pin)
    except SourceError as e:
        print(f'FAIL: generated-pages — {e}', file=sys.stderr)
        return 1
    existing = on_disk(owned)

    if not check:
        for rel, text in pages.items():
            path = os.path.join(ROOT, rel)
            os.makedirs(os.path.dirname(path), exist_ok=True)
            old = open(path, encoding='utf-8').read() if os.path.exists(path) else None
            if old != text:
                with open(path, 'w', encoding='utf-8') as f:
                    f.write(text)
                print(f'escrito  {rel}')
        for rel in sorted(existing - set(pages)):
            os.remove(os.path.join(ROOT, rel))
            print(f'borrado  {rel} (ya no corresponde a nada del pin)')
        print(f'OK: generated-pages — {len(pages)} páginas al día ({", ".join(families)})')
        return 0

    fails = []
    latest = notes.get('latest')
    for rel, text in pages.items():
        path = os.path.join(ROOT, rel)
        if not os.path.exists(path):
            if latest and rel == f'{POSTS_DIR}/{post_name(latest)}.md':
                fails.append(f'[releases] Quantum {latest}, el set que declara versions.yaml, no tiene post '
                             f'({rel}): el tren lo escribe en el PR de set (bump-set.sh corre este generador; '
                             'a mano: python3 scripts/lib/site-pages.py)')
            else:
                fails.append(f'[{family_of(rel)}] falta {rel}: el pin la genera y el sitio no la publica')
            continue
        old = open(path, encoding='utf-8').read()
        if old != text:
            diff = list(difflib.unified_diff(old.splitlines(), text.splitlines(), 'publicado', 'al pin',
                                             lineterm='', n=0))
            shown = [d for d in diff if not d.startswith(('---', '+++'))][:8]
            fails.append(f'[{family_of(rel)}] {rel} no es lo que el pin genera '
                         f'({sum(1 for d in diff if d[:1] in "+-" and not d.startswith(("---", "+++")))} líneas difieren):\n'
                         + '\n'.join('    ' + d for d in shown))
    for rel in sorted(existing - set(pages)):
        fails.append(f'[{family_of(rel)}] {rel} sobra: el directorio es del generador y nada del pin la produce '
                     '(una página a mano va en website/docs/)')
    if fails:
        for f in fails:
            print(f'FAIL: generated-pages — {f}', file=sys.stderr)
        print('generated-pages: el sitio publica algo que el pin no da. Regenera con '
              'python3 scripts/lib/site-pages.py y commitea el resultado; no se editan a mano.', file=sys.stderr)
        return 1
    print(f'OK: generated-pages — {len(pages)} páginas iguales a lo que genera el pin ({", ".join(families)})'
          + (f'; el último set, Quantum {latest}, tiene su post' if latest else ''))
    return 0


def family_of(rel):
    if rel.startswith(POSTS_DIR):
        return 'releases'
    return 'catalog' if os.path.basename(rel).startswith('catalog') else 'api'


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
