import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar autogenerado desde la estructura de ../nucleus/website/docs.
// (En Fase 2 ensamblamos; el orden curado de Nucleus se puede portar después.)
const sidebars: SidebarsConfig = {
  nucleusSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
