import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar autogenerado desde la estructura de ../quark/website/docs.
// (En Fase 2 ensamblamos; el orden curado de Quark se puede portar después.)
const sidebars: SidebarsConfig = {
  quarkSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
