import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar autogenerado desde la estructura de ../orbit/website/docs.
// El orden lo fija el `sidebar_position` del frontmatter de cada página.
const sidebars: SidebarsConfig = {
  orbitSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
